
services:
  postgres:
    image: 'postgres:16'
    container_name: 'inventory-postgres'
    environment:
      - 'POSTGRES_DB=inventory'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
